spring:
  datasource:
    url: jdbc:mysql://10.10.1.153:3306/xckzdb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: xckz
    password: Rx6i62XffWa4CiFm
mqtt:
  test:
    publish: false
